import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

   tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'POS Sales Microservice', // Esto será el nombre que aparece en el sidebar
      items: [
         {
          type: 'autogenerated',
          dirName: 'pos-sales',
        },
      ], // Ruta relativa al archivo md
    },
     {
      type: 'category',
      label: 'E-commerce Sales Microservice',
      items: [
        {
          type: 'autogenerated',
          dirName: 'e-commerce', // todos los archivos de esta otra carpeta
        },
      ],
    },
    {
      type: 'link',
      label: '🚀 Interactive API',
      href: '/api',
    },
  ],
  // But you can create a sidebar manually
  // tutorialSidebar: [
  //   'intro', // id de tu intro.md
  //   // otros documentos si los agregas
  // ],
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
