openapi: 3.0.3
info:
  title: Bamboo Cloud Services API
  description: |
    API documentation for Bamboo Cloud Services microservices.
    This system integrates with external systems from China like KingDee and Smart Link
    to centralize and manage sales information from different channels.
  version: 1.0.0
  contact:
    name: Bamboo Team
    email: support@bamboo.com

servers:
  - url: https://ecommercestoreorders-fgaxd7axcnezhnbh.westus-01.azurewebsites.net
    description: Production E-commerce Server
  - url: https://possales-fgaxd7axcnezhnbh.westus-01.azurewebsites.net  
    description: Production POS Sales Server

tags:
  - name: E-commerce
    description: Operations for e-commerce sales management
  - name: POS Sales
    description: Operations for Point of Sale transactions

paths:
  /api/StoreSale:
    post:
      tags:
        - E-commerce
      summary: Create Store Sale Order
      description: Creates a new store sale order for e-commerce transactions
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
            example:
              customerCode: "CHH2A100706"
              customerName: "MEGALUZ S.A. DE C.V."
              remark: "Pedido prueba Ecommerce"
              billDate: "2025-11-10T13:45:00"
              detail:
                - code: "000002"
                  name: "FREIDORA DE AIRE FDA08V"
                  price: 550
                  quantity: 100
                  warehouseId: 1540416
                - code: "000005"
                  name: "FREIDORA DE AIRE FDA09A"
                  price: 380
                  quantity: 200
                  warehouseId: 1540416
      responses:
        '200':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateOrderResponse'
        '400':
          description: Bad request - Invalid input data
        '401':
          description: Unauthorized - Authentication required
        '500':
          description: Internal server error

  /api/storeorder/cancel/{orderId}:
    delete:
      tags:
        - E-commerce
      summary: Cancel Store Order
      description: Cancels an existing store order
      security:
        - ApiKeyAuth: []
      parameters:
        - name: orderId
          in: path
          required: true
          description: The ID of the order to cancel
          schema:
            type: integer
            example: 12345
        - name: warehouseId
          in: query
          required: true
          description: The warehouse ID associated with the order
          schema:
            type: integer
            example: 2
      responses:
        '200':
          description: Order cancelled successfully
        '401':
          description: Unauthorized - Invalid or missing API key
        '404':
          description: Order not found
        '500':
          description: Internal server error

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: API Key for authentication

  schemas:
    CreateOrderRequest:
      type: object
      required:
        - customerCode
        - customerName
        - billDate
        - detail
      properties:
        customerCode:
          type: string
          description: Unique customer code
          example: "CHH2A100706"
        customerName:
          type: string
          description: Customer company name
          example: "MEGALUZ S.A. DE C.V."
        remark:
          type: string
          description: Additional notes or remarks for the order
          example: "Pedido prueba Ecommerce"
        billDate:
          type: string
          format: date-time
          description: Date and time of the bill
          example: "2025-11-10T13:45:00"
        detail:
          type: array
          items:
            $ref: '#/components/schemas/OrderDetail'

    OrderDetail:
      type: object
      required:
        - code
        - name
        - price
        - quantity
        - warehouseId
      properties:
        code:
          type: string
          description: Product code
          example: "000002"
        name:
          type: string
          description: Product name
          example: "FREIDORA DE AIRE FDA08V"
        price:
          type: number
          format: decimal
          description: Unit price of the product
          example: 550
        quantity:
          type: integer
          description: Quantity ordered
          example: 100
        warehouseId:
          type: integer
          description: Warehouse identifier
          example: 1540416

    CreateOrderResponse:
      type: object
      properties:
        orderId:
          type: integer
          description: Generated order ID
          example: 12345
        status:
          type: string
          description: Order status
          example: "created"
        message:
          type: string
          description: Response message
          example: "Order created successfully"