openapi: 3.0.3
info:
  title: Bamboo Cloud Services API
  description: |
    API documentation for Bamboo Cloud Services microservices.
    This system integrates with external systems from China like KingDee and Smart Link
    to centralize and manage sales information from different channels.
  version: 1.0.0
  contact:
    name: Bamboo Team
    email: support@bamboo.com

servers:
  - url: https://ecommercestoreorders-fgaxd7axcnezhnbh.westus-01.azurewebsites.net
    description: Production E-commerce Server
  - url: https://possales-fgaxd7axcnezhnbh.westus-01.azurewebsites.net  
    description: Production POS Sales Server

tags:
  - name: E-commerce
    description: Operations for e-commerce sales management
  - name: POS Sales
    description: Operations for Point of Sale transactions

paths:
  /api/StoreSale:
    post:
      tags:
        - E-commerce
      summary: Create Store Sale Order
      description: Creates a new store sale order for e-commerce transactions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
            example:
              CustomerCode: "COD00011"
              CustomerName: "Delta Corporate Inc."
              Remark: "Order requested for the IT department."
              BillDate: "2025-12-01"
              OrderDetails:
                - Code: "NET-900"
                  Name: "Cisco Router RV340"
                  Price: 5250.99
                  Quantity: 1
                  WarehouseId: 2
      responses:
        '200':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateOrderResponse'
        '400':
          description: Bad request - Invalid input data
        '401':
          description: Unauthorized - Authentication required
        '500':
          description: Internal server error

  /api/storeorder/cancel/{orderId}:
    delete:
      tags:
        - E-commerce
      summary: Cancel Store Order
      description: Cancels an existing store order
      security:
        - BearerAuth: []
      parameters:
        - name: orderId
          in: path
          required: true
          description: The ID of the order to cancel
          schema:
            type: integer
            example: 12345
        - name: warehouseId
          in: query
          required: true
          description: The warehouse ID associated with the order
          schema:
            type: integer
            example: 2
      responses:
        '200':
          description: Order cancelled successfully
        '401':
          description: Unauthorized - Invalid or missing authentication token
        '404':
          description: Order not found
        '500':
          description: Internal server error

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Enter your bearer token

  schemas:
    CreateOrderRequest:
      type: object
      required:
        - CustomerCode
        - CustomerName
        - BillDate
        - OrderDetails
      properties:
        CustomerCode:
          type: string
          description: Unique customer code
          example: "COD00011"
        CustomerName:
          type: string
          description: Customer company name
          example: "Delta Corporate Inc."
        Remark:
          type: string
          description: Additional notes or remarks for the order
          example: "Order requested for the IT department."
        BillDate:
          type: string
          format: date
          description: Date of the bill
          example: "2025-12-01"
        OrderDetails:
          type: array
          items:
            $ref: '#/components/schemas/OrderDetail'

    OrderDetail:
      type: object
      required:
        - Code
        - Name
        - Price
        - Quantity
        - WarehouseId
      properties:
        Code:
          type: string
          description: Product code
          example: "NET-900"
        Name:
          type: string
          description: Product name
          example: "Cisco Router RV340"
        Price:
          type: number
          format: decimal
          description: Unit price of the product
          example: 5250.99
        Quantity:
          type: integer
          description: Quantity ordered
          example: 1
        WarehouseId:
          type: integer
          description: Warehouse identifier
          example: 2

    CreateOrderResponse:
      type: object
      properties:
        orderId:
          type: integer
          description: Generated order ID
          example: 12345
        status:
          type: string
          description: Order status
          example: "created"
        message:
          type: string
          description: Response message
          example: "Order created successfully"